# Generated by Django 4.1.1 on 2023-08-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_actualizado_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('modificado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
