# Generated by Django 4.0.5 on 2023-07-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(choices=[('FIAT', 'Fiat'), ('CHEVROLET', 'Chevrolet'), ('FORD', 'Ford'), ('TOYOTA', 'Toyota')], default='Ford', max_length=20)),
                ('Modelo', models.CharField(max_length=100)),
                ('Serial_carroceria', models.CharField(max_length=50)),
                ('Serial_motor', models.CharField(max_length=50)),
                ('Particular', models.CharField(max_length=100)),
                ('Categoria', models.CharField(choices=[('PARTICULAR', 'Particular'), ('TRANSPORTE', 'Transporte'), ('CARGA', 'Carga')], default='Particular', max_length=20)),
                ('Precio', models.FloatField()),
                ('Fecha_creacion', models.DateField(auto_now_add=True)),
                ('Fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
