# Generated by Django 4.0.5 on 2023-07-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='VehiculoModel',
        ),
    ]
